<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIleJ2Pf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIleJ2Pf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIleJ2Pf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIleJ2Pf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIleJ2Pf\App_KernelDevDebugContainer([
    'container.build_hash' => 'IleJ2Pf',
    'container.build_id' => '2e3b1044',
    'container.build_time' => 1622705955,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIleJ2Pf');
